version: "3.1"

services:
  webserver:
    image: docker.io/defensayseguridad/cadete:v02
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
    links:
      - database
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
      PMA_PORT: 8081
      MYSQL_ROOT_PASSWORD: 0Tf06171
      MYSQL_USER: user
      MYSQL_PASSWORD: PMU36r7PKDs/[8E9
      HOST_MACHINE_MYSQL_PORT: 3306
  
  database:
    build:
      context: "./bin/mysql8"
    restart: "always"
    ports:
      - "3306:3306"
    volumes:
      - database_volumen:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0Tf06171
      MYSQL_USER: user
      MYSQL_PASSWORD: PMU36r7PKDs/[8E9
  phpmyadmin:
    image: phpmyadmin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 0Tf06171
      MYSQL_USER: user
      MYSQL_PASSWORD: PMU36r7PKDs/[8E9
      MYSQL_ROOT_PASSWORD: 0Tf06171
      
    ports:
      - "8081:80"
      - "8443:443"
volumes:
  database_volumen:
 
  
